package org.andromda.utils;

import junit.framework.TestCase;

public class JavaTypeConverterTest 
    extends TestCase
{

    public static final class ExpectedResult
    {
        private final String fromType;
        private final String toType;
        private final String expected;
        
        public ExpectedResult(
            String fromType,
            String toType,
            String expected)
        {
            this.fromType = fromType;
            this.toType = toType;
            this.expected = expected;
        }
    }
    
    
    private final static ExpectedResult[] expected =
    {
        new ExpectedResult("int", "int", "sourceVal"),
        new ExpectedResult("int", "int[]", null),
        new ExpectedResult("int", "long", "(long)sourceVal"),
        new ExpectedResult("int", "long[]", null),
        new ExpectedResult("int", "double", "(double)sourceVal"),
        new ExpectedResult("int", "double[]", null),
        new ExpectedResult("int", "float", "(float)sourceVal"),
        new ExpectedResult("int", "float[]", null),
        new ExpectedResult("int", "boolean", "(sourceVal != 0)"),
        new ExpectedResult("int", "boolean[]", null),
        new ExpectedResult("int", "java.lang.Integer", "new java.lang.Integer(sourceVal)"),
        new ExpectedResult("int", "java.lang.Integer[]", null),
        new ExpectedResult("int", "java.lang.Long", "new java.lang.Long((long)sourceVal)"),
        new ExpectedResult("int", "java.lang.Long[]", null),
        new ExpectedResult("int", "java.lang.Double", "new java.lang.Double((double)sourceVal)"),
        new ExpectedResult("int", "java.lang.Double[]", null),
        new ExpectedResult("int", "java.lang.Float", "new java.lang.Float((float)sourceVal)"),
        new ExpectedResult("int", "java.lang.Float[]", null),
        new ExpectedResult("int", "java.lang.Boolean", "new java.lang.Boolean((sourceVal != 0))"),
        new ExpectedResult("int", "java.lang.Boolean[]", null),
        new ExpectedResult("int", "java.util.Date", null),
        new ExpectedResult("int", "java.util.Date[]", null),
        new ExpectedResult("int", "java.sql.Timestamp", null),
        new ExpectedResult("int", "java.sql.Timestamp[]", null),
        new ExpectedResult("int", "java.sql.Time", null),
        new ExpectedResult("int", "java.sql.Time[]", null),
        new ExpectedResult("int", "java.sql.Date", null),
        new ExpectedResult("int", "java.sql.Date[]", null),
        new ExpectedResult("int", "java.lang.String", "java.lang.String.valueOf(sourceVal)"),
        new ExpectedResult("int", "java.lang.String[]", null),
        new ExpectedResult("int", "com.example.UserClass1", null),
        new ExpectedResult("int", "com.example.UserClass1[]", null),
        new ExpectedResult("int", "com.example.UserClass2", null),
        new ExpectedResult("int", "com.example.UserClass2[]", null),
        new ExpectedResult("int[]", "int", null),
        new ExpectedResult("int[]", "int[]", "sourceVal"),
        new ExpectedResult("int[]", "long", null),
        new ExpectedResult("int[]", "long[]", null),
        new ExpectedResult("int[]", "double", null),
        new ExpectedResult("int[]", "double[]", null),
        new ExpectedResult("int[]", "float", null),
        new ExpectedResult("int[]", "float[]", null),
        new ExpectedResult("int[]", "boolean", null),
        new ExpectedResult("int[]", "boolean[]", null),
        new ExpectedResult("int[]", "java.lang.Integer", null),
        new ExpectedResult("int[]", "java.lang.Integer[]", null),
        new ExpectedResult("int[]", "java.lang.Long", null),
        new ExpectedResult("int[]", "java.lang.Long[]", null),
        new ExpectedResult("int[]", "java.lang.Double", null),
        new ExpectedResult("int[]", "java.lang.Double[]", null),
        new ExpectedResult("int[]", "java.lang.Float", null),
        new ExpectedResult("int[]", "java.lang.Float[]", null),
        new ExpectedResult("int[]", "java.lang.Boolean", null),
        new ExpectedResult("int[]", "java.lang.Boolean[]", null),
        new ExpectedResult("int[]", "java.util.Date", null),
        new ExpectedResult("int[]", "java.util.Date[]", null),
        new ExpectedResult("int[]", "java.sql.Timestamp", null),
        new ExpectedResult("int[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("int[]", "java.sql.Time", null),
        new ExpectedResult("int[]", "java.sql.Time[]", null),
        new ExpectedResult("int[]", "java.sql.Date", null),
        new ExpectedResult("int[]", "java.sql.Date[]", null),
        new ExpectedResult("int[]", "java.lang.String", null),
        new ExpectedResult("int[]", "java.lang.String[]", null),
        new ExpectedResult("int[]", "com.example.UserClass1", null),
        new ExpectedResult("int[]", "com.example.UserClass1[]", null),
        new ExpectedResult("int[]", "com.example.UserClass2", null),
        new ExpectedResult("int[]", "com.example.UserClass2[]", null),
        new ExpectedResult("long", "int", "(int)sourceVal"),
        new ExpectedResult("long", "int[]", null),
        new ExpectedResult("long", "long", "sourceVal"),
        new ExpectedResult("long", "long[]", null),
        new ExpectedResult("long", "double", "(double)sourceVal"),
        new ExpectedResult("long", "double[]", null),
        new ExpectedResult("long", "float", "(float)sourceVal"),
        new ExpectedResult("long", "float[]", null),
        new ExpectedResult("long", "boolean", "(sourceVal != 0)"),
        new ExpectedResult("long", "boolean[]", null),
        new ExpectedResult("long", "java.lang.Integer", "new java.lang.Integer((int)sourceVal)"),
        new ExpectedResult("long", "java.lang.Integer[]", null),
        new ExpectedResult("long", "java.lang.Long", "new java.lang.Long(sourceVal)"),
        new ExpectedResult("long", "java.lang.Long[]", null),
        new ExpectedResult("long", "java.lang.Double", "new java.lang.Double((double)sourceVal)"),
        new ExpectedResult("long", "java.lang.Double[]", null),
        new ExpectedResult("long", "java.lang.Float", "new java.lang.Float((float)sourceVal)"),
        new ExpectedResult("long", "java.lang.Float[]", null),
        new ExpectedResult("long", "java.lang.Boolean", "new java.lang.Boolean((sourceVal != 0))"),
        new ExpectedResult("long", "java.lang.Boolean[]", null),
        new ExpectedResult("long", "java.util.Date", "new java.util.Date(sourceVal)"),
        new ExpectedResult("long", "java.util.Date[]", null),
        new ExpectedResult("long", "java.sql.Timestamp", "new java.sql.Timestamp(sourceVal)"),
        new ExpectedResult("long", "java.sql.Timestamp[]", null),
        new ExpectedResult("long", "java.sql.Time", "new java.sql.Time(sourceVal)"),
        new ExpectedResult("long", "java.sql.Time[]", null),
        new ExpectedResult("long", "java.sql.Date", "new java.sql.Date(sourceVal)"),
        new ExpectedResult("long", "java.sql.Date[]", null),
        new ExpectedResult("long", "java.lang.String", "java.lang.String.valueOf(sourceVal)"),
        new ExpectedResult("long", "java.lang.String[]", null),
        new ExpectedResult("long", "com.example.UserClass1", null),
        new ExpectedResult("long", "com.example.UserClass1[]", null),
        new ExpectedResult("long", "com.example.UserClass2", null),
        new ExpectedResult("long", "com.example.UserClass2[]", null),
        new ExpectedResult("long[]", "int", null),
        new ExpectedResult("long[]", "int[]", null),
        new ExpectedResult("long[]", "long", null),
        new ExpectedResult("long[]", "long[]", "sourceVal"),
        new ExpectedResult("long[]", "double", null),
        new ExpectedResult("long[]", "double[]", null),
        new ExpectedResult("long[]", "float", null),
        new ExpectedResult("long[]", "float[]", null),
        new ExpectedResult("long[]", "boolean", null),
        new ExpectedResult("long[]", "boolean[]", null),
        new ExpectedResult("long[]", "java.lang.Integer", null),
        new ExpectedResult("long[]", "java.lang.Integer[]", null),
        new ExpectedResult("long[]", "java.lang.Long", null),
        new ExpectedResult("long[]", "java.lang.Long[]", null),
        new ExpectedResult("long[]", "java.lang.Double", null),
        new ExpectedResult("long[]", "java.lang.Double[]", null),
        new ExpectedResult("long[]", "java.lang.Float", null),
        new ExpectedResult("long[]", "java.lang.Float[]", null),
        new ExpectedResult("long[]", "java.lang.Boolean", null),
        new ExpectedResult("long[]", "java.lang.Boolean[]", null),
        new ExpectedResult("long[]", "java.util.Date", null),
        new ExpectedResult("long[]", "java.util.Date[]", null),
        new ExpectedResult("long[]", "java.sql.Timestamp", null),
        new ExpectedResult("long[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("long[]", "java.sql.Time", null),
        new ExpectedResult("long[]", "java.sql.Time[]", null),
        new ExpectedResult("long[]", "java.sql.Date", null),
        new ExpectedResult("long[]", "java.sql.Date[]", null),
        new ExpectedResult("long[]", "java.lang.String", null),
        new ExpectedResult("long[]", "java.lang.String[]", null),
        new ExpectedResult("long[]", "com.example.UserClass1", null),
        new ExpectedResult("long[]", "com.example.UserClass1[]", null),
        new ExpectedResult("long[]", "com.example.UserClass2", null),
        new ExpectedResult("long[]", "com.example.UserClass2[]", null),
        new ExpectedResult("double", "int", "(int)sourceVal"),
        new ExpectedResult("double", "int[]", null),
        new ExpectedResult("double", "long", "(long)sourceVal"),
        new ExpectedResult("double", "long[]", null),
        new ExpectedResult("double", "double", "sourceVal"),
        new ExpectedResult("double", "double[]", null),
        new ExpectedResult("double", "float", "(float)sourceVal"),
        new ExpectedResult("double", "float[]", null),
        new ExpectedResult("double", "boolean", "(sourceVal != 0.0)"),
        new ExpectedResult("double", "boolean[]", null),
        new ExpectedResult("double", "java.lang.Integer", "new java.lang.Integer((int)sourceVal)"),
        new ExpectedResult("double", "java.lang.Integer[]", null),
        new ExpectedResult("double", "java.lang.Long", "new java.lang.Long((long)sourceVal)"),
        new ExpectedResult("double", "java.lang.Long[]", null),
        new ExpectedResult("double", "java.lang.Double", "new java.lang.Double(sourceVal)"),
        new ExpectedResult("double", "java.lang.Double[]", null),
        new ExpectedResult("double", "java.lang.Float", "new java.lang.Float((float)sourceVal)"),
        new ExpectedResult("double", "java.lang.Float[]", null),
        new ExpectedResult("double", "java.lang.Boolean", "new java.lang.Boolean((sourceVal != 0.0))"),
        new ExpectedResult("double", "java.lang.Boolean[]", null),
        new ExpectedResult("double", "java.util.Date", null),
        new ExpectedResult("double", "java.util.Date[]", null),
        new ExpectedResult("double", "java.sql.Timestamp", null),
        new ExpectedResult("double", "java.sql.Timestamp[]", null),
        new ExpectedResult("double", "java.sql.Time", null),
        new ExpectedResult("double", "java.sql.Time[]", null),
        new ExpectedResult("double", "java.sql.Date", null),
        new ExpectedResult("double", "java.sql.Date[]", null),
        new ExpectedResult("double", "java.lang.String", "java.lang.String.valueOf(sourceVal)"),
        new ExpectedResult("double", "java.lang.String[]", null),
        new ExpectedResult("double", "com.example.UserClass1", null),
        new ExpectedResult("double", "com.example.UserClass1[]", null),
        new ExpectedResult("double", "com.example.UserClass2", null),
        new ExpectedResult("double", "com.example.UserClass2[]", null),
        new ExpectedResult("double[]", "int", null),
        new ExpectedResult("double[]", "int[]", null),
        new ExpectedResult("double[]", "long", null),
        new ExpectedResult("double[]", "long[]", null),
        new ExpectedResult("double[]", "double", null),
        new ExpectedResult("double[]", "double[]", "sourceVal"),
        new ExpectedResult("double[]", "float", null),
        new ExpectedResult("double[]", "float[]", null),
        new ExpectedResult("double[]", "boolean", null),
        new ExpectedResult("double[]", "boolean[]", null),
        new ExpectedResult("double[]", "java.lang.Integer", null),
        new ExpectedResult("double[]", "java.lang.Integer[]", null),
        new ExpectedResult("double[]", "java.lang.Long", null),
        new ExpectedResult("double[]", "java.lang.Long[]", null),
        new ExpectedResult("double[]", "java.lang.Double", null),
        new ExpectedResult("double[]", "java.lang.Double[]", null),
        new ExpectedResult("double[]", "java.lang.Float", null),
        new ExpectedResult("double[]", "java.lang.Float[]", null),
        new ExpectedResult("double[]", "java.lang.Boolean", null),
        new ExpectedResult("double[]", "java.lang.Boolean[]", null),
        new ExpectedResult("double[]", "java.util.Date", null),
        new ExpectedResult("double[]", "java.util.Date[]", null),
        new ExpectedResult("double[]", "java.sql.Timestamp", null),
        new ExpectedResult("double[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("double[]", "java.sql.Time", null),
        new ExpectedResult("double[]", "java.sql.Time[]", null),
        new ExpectedResult("double[]", "java.sql.Date", null),
        new ExpectedResult("double[]", "java.sql.Date[]", null),
        new ExpectedResult("double[]", "java.lang.String", null),
        new ExpectedResult("double[]", "java.lang.String[]", null),
        new ExpectedResult("double[]", "com.example.UserClass1", null),
        new ExpectedResult("double[]", "com.example.UserClass1[]", null),
        new ExpectedResult("double[]", "com.example.UserClass2", null),
        new ExpectedResult("double[]", "com.example.UserClass2[]", null),
        new ExpectedResult("float", "int", "(int)sourceVal"),
        new ExpectedResult("float", "int[]", null),
        new ExpectedResult("float", "long", "(long)sourceVal"),
        new ExpectedResult("float", "long[]", null),
        new ExpectedResult("float", "double", "(double)sourceVal"),
        new ExpectedResult("float", "double[]", null),
        new ExpectedResult("float", "float", "sourceVal"),
        new ExpectedResult("float", "float[]", null),
        new ExpectedResult("float", "boolean", "(sourceVal != 0.0f)"),
        new ExpectedResult("float", "boolean[]", null),
        new ExpectedResult("float", "java.lang.Integer", "new java.lang.Integer((int)sourceVal)"),
        new ExpectedResult("float", "java.lang.Integer[]", null),
        new ExpectedResult("float", "java.lang.Long", "new java.lang.Long((long)sourceVal)"),
        new ExpectedResult("float", "java.lang.Long[]", null),
        new ExpectedResult("float", "java.lang.Double", "new java.lang.Double((double)sourceVal)"),
        new ExpectedResult("float", "java.lang.Double[]", null),
        new ExpectedResult("float", "java.lang.Float", "new java.lang.Float(sourceVal)"),
        new ExpectedResult("float", "java.lang.Float[]", null),
        new ExpectedResult("float", "java.lang.Boolean", "new java.lang.Boolean((sourceVal != 0.0f))"),
        new ExpectedResult("float", "java.lang.Boolean[]", null),
        new ExpectedResult("float", "java.util.Date", null),
        new ExpectedResult("float", "java.util.Date[]", null),
        new ExpectedResult("float", "java.sql.Timestamp", null),
        new ExpectedResult("float", "java.sql.Timestamp[]", null),
        new ExpectedResult("float", "java.sql.Time", null),
        new ExpectedResult("float", "java.sql.Time[]", null),
        new ExpectedResult("float", "java.sql.Date", null),
        new ExpectedResult("float", "java.sql.Date[]", null),
        new ExpectedResult("float", "java.lang.String", "java.lang.String.valueOf(sourceVal)"),
        new ExpectedResult("float", "java.lang.String[]", null),
        new ExpectedResult("float", "com.example.UserClass1", null),
        new ExpectedResult("float", "com.example.UserClass1[]", null),
        new ExpectedResult("float", "com.example.UserClass2", null),
        new ExpectedResult("float", "com.example.UserClass2[]", null),
        new ExpectedResult("float[]", "int", null),
        new ExpectedResult("float[]", "int[]", null),
        new ExpectedResult("float[]", "long", null),
        new ExpectedResult("float[]", "long[]", null),
        new ExpectedResult("float[]", "double", null),
        new ExpectedResult("float[]", "double[]", null),
        new ExpectedResult("float[]", "float", null),
        new ExpectedResult("float[]", "float[]", "sourceVal"),
        new ExpectedResult("float[]", "boolean", null),
        new ExpectedResult("float[]", "boolean[]", null),
        new ExpectedResult("float[]", "java.lang.Integer", null),
        new ExpectedResult("float[]", "java.lang.Integer[]", null),
        new ExpectedResult("float[]", "java.lang.Long", null),
        new ExpectedResult("float[]", "java.lang.Long[]", null),
        new ExpectedResult("float[]", "java.lang.Double", null),
        new ExpectedResult("float[]", "java.lang.Double[]", null),
        new ExpectedResult("float[]", "java.lang.Float", null),
        new ExpectedResult("float[]", "java.lang.Float[]", null),
        new ExpectedResult("float[]", "java.lang.Boolean", null),
        new ExpectedResult("float[]", "java.lang.Boolean[]", null),
        new ExpectedResult("float[]", "java.util.Date", null),
        new ExpectedResult("float[]", "java.util.Date[]", null),
        new ExpectedResult("float[]", "java.sql.Timestamp", null),
        new ExpectedResult("float[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("float[]", "java.sql.Time", null),
        new ExpectedResult("float[]", "java.sql.Time[]", null),
        new ExpectedResult("float[]", "java.sql.Date", null),
        new ExpectedResult("float[]", "java.sql.Date[]", null),
        new ExpectedResult("float[]", "java.lang.String", null),
        new ExpectedResult("float[]", "java.lang.String[]", null),
        new ExpectedResult("float[]", "com.example.UserClass1", null),
        new ExpectedResult("float[]", "com.example.UserClass1[]", null),
        new ExpectedResult("float[]", "com.example.UserClass2", null),
        new ExpectedResult("float[]", "com.example.UserClass2[]", null),
        new ExpectedResult("boolean", "int", "(sourceVal ? 1 : 0)"),
        new ExpectedResult("boolean", "int[]", null),
        new ExpectedResult("boolean", "long", "(sourceVal ? 1 : 0)"),
        new ExpectedResult("boolean", "long[]", null),
        new ExpectedResult("boolean", "double", "(sourceVal ? 1.0 : 0.0)"),
        new ExpectedResult("boolean", "double[]", null),
        new ExpectedResult("boolean", "float", "(sourceVal ? 1.0f : 0.0f)"),
        new ExpectedResult("boolean", "float[]", null),
        new ExpectedResult("boolean", "boolean", "sourceVal"),
        new ExpectedResult("boolean", "boolean[]", null),
        new ExpectedResult("boolean", "java.lang.Integer", "new java.lang.Integer((sourceVal ? 1 : 0))"),
        new ExpectedResult("boolean", "java.lang.Integer[]", null),
        new ExpectedResult("boolean", "java.lang.Long", "new java.lang.Long((sourceVal ? 1 : 0))"),
        new ExpectedResult("boolean", "java.lang.Long[]", null),
        new ExpectedResult("boolean", "java.lang.Double", "new java.lang.Double((sourceVal ? 1.0 : 0.0))"),
        new ExpectedResult("boolean", "java.lang.Double[]", null),
        new ExpectedResult("boolean", "java.lang.Float", "new java.lang.Float((sourceVal ? 1.0f : 0.0f))"),
        new ExpectedResult("boolean", "java.lang.Float[]", null),
        new ExpectedResult("boolean", "java.lang.Boolean", "new java.lang.Boolean(sourceVal)"),
        new ExpectedResult("boolean", "java.lang.Boolean[]", null),
        new ExpectedResult("boolean", "java.util.Date", null),
        new ExpectedResult("boolean", "java.util.Date[]", null),
        new ExpectedResult("boolean", "java.sql.Timestamp", null),
        new ExpectedResult("boolean", "java.sql.Timestamp[]", null),
        new ExpectedResult("boolean", "java.sql.Time", null),
        new ExpectedResult("boolean", "java.sql.Time[]", null),
        new ExpectedResult("boolean", "java.sql.Date", null),
        new ExpectedResult("boolean", "java.sql.Date[]", null),
        new ExpectedResult("boolean", "java.lang.String", "java.lang.String.valueOf(sourceVal)"),
        new ExpectedResult("boolean", "java.lang.String[]", null),
        new ExpectedResult("boolean", "com.example.UserClass1", null),
        new ExpectedResult("boolean", "com.example.UserClass1[]", null),
        new ExpectedResult("boolean", "com.example.UserClass2", null),
        new ExpectedResult("boolean", "com.example.UserClass2[]", null),
        new ExpectedResult("boolean[]", "int", null),
        new ExpectedResult("boolean[]", "int[]", null),
        new ExpectedResult("boolean[]", "long", null),
        new ExpectedResult("boolean[]", "long[]", null),
        new ExpectedResult("boolean[]", "double", null),
        new ExpectedResult("boolean[]", "double[]", null),
        new ExpectedResult("boolean[]", "float", null),
        new ExpectedResult("boolean[]", "float[]", null),
        new ExpectedResult("boolean[]", "boolean", null),
        new ExpectedResult("boolean[]", "boolean[]", "sourceVal"),
        new ExpectedResult("boolean[]", "java.lang.Integer", null),
        new ExpectedResult("boolean[]", "java.lang.Integer[]", null),
        new ExpectedResult("boolean[]", "java.lang.Long", null),
        new ExpectedResult("boolean[]", "java.lang.Long[]", null),
        new ExpectedResult("boolean[]", "java.lang.Double", null),
        new ExpectedResult("boolean[]", "java.lang.Double[]", null),
        new ExpectedResult("boolean[]", "java.lang.Float", null),
        new ExpectedResult("boolean[]", "java.lang.Float[]", null),
        new ExpectedResult("boolean[]", "java.lang.Boolean", null),
        new ExpectedResult("boolean[]", "java.lang.Boolean[]", null),
        new ExpectedResult("boolean[]", "java.util.Date", null),
        new ExpectedResult("boolean[]", "java.util.Date[]", null),
        new ExpectedResult("boolean[]", "java.sql.Timestamp", null),
        new ExpectedResult("boolean[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("boolean[]", "java.sql.Time", null),
        new ExpectedResult("boolean[]", "java.sql.Time[]", null),
        new ExpectedResult("boolean[]", "java.sql.Date", null),
        new ExpectedResult("boolean[]", "java.sql.Date[]", null),
        new ExpectedResult("boolean[]", "java.lang.String", null),
        new ExpectedResult("boolean[]", "java.lang.String[]", null),
        new ExpectedResult("boolean[]", "com.example.UserClass1", null),
        new ExpectedResult("boolean[]", "com.example.UserClass1[]", null),
        new ExpectedResult("boolean[]", "com.example.UserClass2", null),
        new ExpectedResult("boolean[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Integer", "int", "(sourceVal == null ? 0 : sourceVal.intValue())"),
        new ExpectedResult("java.lang.Integer", "int[]", null),
        new ExpectedResult("java.lang.Integer", "long", "(long)(sourceVal == null ? 0 : sourceVal.intValue())"),
        new ExpectedResult("java.lang.Integer", "long[]", null),
        new ExpectedResult("java.lang.Integer", "double", "(double)(sourceVal == null ? 0 : sourceVal.intValue())"),
        new ExpectedResult("java.lang.Integer", "double[]", null),
        new ExpectedResult("java.lang.Integer", "float", "(float)(sourceVal == null ? 0 : sourceVal.intValue())"),
        new ExpectedResult("java.lang.Integer", "float[]", null),
        new ExpectedResult("java.lang.Integer", "boolean", "((sourceVal == null ? 0 : sourceVal.intValue()) != 0)"),
        new ExpectedResult("java.lang.Integer", "boolean[]", null),
        new ExpectedResult("java.lang.Integer", "java.lang.Integer", "sourceVal"),
        new ExpectedResult("java.lang.Integer", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Integer", "java.lang.Long", "new java.lang.Long((long)(sourceVal == null ? 0 : sourceVal.intValue()))"),
        new ExpectedResult("java.lang.Integer", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Integer", "java.lang.Double", "new java.lang.Double((double)(sourceVal == null ? 0 : sourceVal.intValue()))"),
        new ExpectedResult("java.lang.Integer", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Integer", "java.lang.Float", "new java.lang.Float((float)(sourceVal == null ? 0 : sourceVal.intValue()))"),
        new ExpectedResult("java.lang.Integer", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Integer", "java.lang.Boolean", "new java.lang.Boolean(((sourceVal == null ? 0 : sourceVal.intValue()) != 0))"),
        new ExpectedResult("java.lang.Integer", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Integer", "java.util.Date", null),
        new ExpectedResult("java.lang.Integer", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Integer", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Integer", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Integer", "java.sql.Time", null),
        new ExpectedResult("java.lang.Integer", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Integer", "java.sql.Date", null),
        new ExpectedResult("java.lang.Integer", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Integer", "java.lang.String", "(sourceVal == null ? null : sourceVal.toString())"),
        new ExpectedResult("java.lang.Integer", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Integer", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Integer", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Integer", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Integer", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Integer[]", "int", null),
        new ExpectedResult("java.lang.Integer[]", "int[]", null),
        new ExpectedResult("java.lang.Integer[]", "long", null),
        new ExpectedResult("java.lang.Integer[]", "long[]", null),
        new ExpectedResult("java.lang.Integer[]", "double", null),
        new ExpectedResult("java.lang.Integer[]", "double[]", null),
        new ExpectedResult("java.lang.Integer[]", "float", null),
        new ExpectedResult("java.lang.Integer[]", "float[]", null),
        new ExpectedResult("java.lang.Integer[]", "boolean", null),
        new ExpectedResult("java.lang.Integer[]", "boolean[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Integer", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Integer[]", "sourceVal"),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Long", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Double", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Float", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Boolean", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.util.Date", null),
        new ExpectedResult("java.lang.Integer[]", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Integer[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.sql.Time", null),
        new ExpectedResult("java.lang.Integer[]", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.sql.Date", null),
        new ExpectedResult("java.lang.Integer[]", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.String", null),
        new ExpectedResult("java.lang.Integer[]", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Integer[]", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Integer[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Integer[]", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Integer[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Long", "int", "(int)(sourceVal == null ? 0 : sourceVal.longValue())"),
        new ExpectedResult("java.lang.Long", "int[]", null),
        new ExpectedResult("java.lang.Long", "long", "(sourceVal == null ? 0 : sourceVal.longValue())"),
        new ExpectedResult("java.lang.Long", "long[]", null),
        new ExpectedResult("java.lang.Long", "double", "(double)(sourceVal == null ? 0 : sourceVal.longValue())"),
        new ExpectedResult("java.lang.Long", "double[]", null),
        new ExpectedResult("java.lang.Long", "float", "(float)(sourceVal == null ? 0 : sourceVal.longValue())"),
        new ExpectedResult("java.lang.Long", "float[]", null),
        new ExpectedResult("java.lang.Long", "boolean", "((sourceVal == null ? 0 : sourceVal.longValue()) != 0)"),
        new ExpectedResult("java.lang.Long", "boolean[]", null),
        new ExpectedResult("java.lang.Long", "java.lang.Integer", "new java.lang.Integer((int)(sourceVal == null ? 0 : sourceVal.longValue()))"),
        new ExpectedResult("java.lang.Long", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Long", "java.lang.Long", "sourceVal"),
        new ExpectedResult("java.lang.Long", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Long", "java.lang.Double", "new java.lang.Double((double)(sourceVal == null ? 0 : sourceVal.longValue()))"),
        new ExpectedResult("java.lang.Long", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Long", "java.lang.Float", "new java.lang.Float((float)(sourceVal == null ? 0 : sourceVal.longValue()))"),
        new ExpectedResult("java.lang.Long", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Long", "java.lang.Boolean", "new java.lang.Boolean(((sourceVal == null ? 0 : sourceVal.longValue()) != 0))"),
        new ExpectedResult("java.lang.Long", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Long", "java.util.Date", "new java.util.Date((sourceVal == null ? 0 : sourceVal.longValue()))"),
        new ExpectedResult("java.lang.Long", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Long", "java.sql.Timestamp", "new java.sql.Timestamp((sourceVal == null ? 0 : sourceVal.longValue()))"),
        new ExpectedResult("java.lang.Long", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Long", "java.sql.Time", "new java.sql.Time((sourceVal == null ? 0 : sourceVal.longValue()))"),
        new ExpectedResult("java.lang.Long", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Long", "java.sql.Date", "new java.sql.Date((sourceVal == null ? 0 : sourceVal.longValue()))"),
        new ExpectedResult("java.lang.Long", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Long", "java.lang.String", "(sourceVal == null ? null : sourceVal.toString())"),
        new ExpectedResult("java.lang.Long", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Long", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Long", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Long", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Long", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Long[]", "int", null),
        new ExpectedResult("java.lang.Long[]", "int[]", null),
        new ExpectedResult("java.lang.Long[]", "long", null),
        new ExpectedResult("java.lang.Long[]", "long[]", null),
        new ExpectedResult("java.lang.Long[]", "double", null),
        new ExpectedResult("java.lang.Long[]", "double[]", null),
        new ExpectedResult("java.lang.Long[]", "float", null),
        new ExpectedResult("java.lang.Long[]", "float[]", null),
        new ExpectedResult("java.lang.Long[]", "boolean", null),
        new ExpectedResult("java.lang.Long[]", "boolean[]", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Integer", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Long", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Long[]", "sourceVal"),
        new ExpectedResult("java.lang.Long[]", "java.lang.Double", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Float", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Boolean", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Long[]", "java.util.Date", null),
        new ExpectedResult("java.lang.Long[]", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Long[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Long[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Long[]", "java.sql.Time", null),
        new ExpectedResult("java.lang.Long[]", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Long[]", "java.sql.Date", null),
        new ExpectedResult("java.lang.Long[]", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.String", null),
        new ExpectedResult("java.lang.Long[]", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Long[]", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Long[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Long[]", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Long[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Double", "int", "(int)(sourceVal == null ? 0.0 : sourceVal.doubleValue())"),
        new ExpectedResult("java.lang.Double", "int[]", null),
        new ExpectedResult("java.lang.Double", "long", "(long)(sourceVal == null ? 0.0 : sourceVal.doubleValue())"),
        new ExpectedResult("java.lang.Double", "long[]", null),
        new ExpectedResult("java.lang.Double", "double", "(sourceVal == null ? 0.0 : sourceVal.doubleValue())"),
        new ExpectedResult("java.lang.Double", "double[]", null),
        new ExpectedResult("java.lang.Double", "float", "(float)(sourceVal == null ? 0.0 : sourceVal.doubleValue())"),
        new ExpectedResult("java.lang.Double", "float[]", null),
        new ExpectedResult("java.lang.Double", "boolean", "((sourceVal == null ? 0.0 : sourceVal.doubleValue()) != 0.0)"),
        new ExpectedResult("java.lang.Double", "boolean[]", null),
        new ExpectedResult("java.lang.Double", "java.lang.Integer", "new java.lang.Integer((int)(sourceVal == null ? 0.0 : sourceVal.doubleValue()))"),
        new ExpectedResult("java.lang.Double", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Double", "java.lang.Long", "new java.lang.Long((long)(sourceVal == null ? 0.0 : sourceVal.doubleValue()))"),
        new ExpectedResult("java.lang.Double", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Double", "java.lang.Double", "sourceVal"),
        new ExpectedResult("java.lang.Double", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Double", "java.lang.Float", "new java.lang.Float((float)(sourceVal == null ? 0.0 : sourceVal.doubleValue()))"),
        new ExpectedResult("java.lang.Double", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Double", "java.lang.Boolean", "new java.lang.Boolean(((sourceVal == null ? 0.0 : sourceVal.doubleValue()) != 0.0))"),
        new ExpectedResult("java.lang.Double", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Double", "java.util.Date", null),
        new ExpectedResult("java.lang.Double", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Double", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Double", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Double", "java.sql.Time", null),
        new ExpectedResult("java.lang.Double", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Double", "java.sql.Date", null),
        new ExpectedResult("java.lang.Double", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Double", "java.lang.String", "(sourceVal == null ? null : sourceVal.toString())"),
        new ExpectedResult("java.lang.Double", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Double", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Double", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Double", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Double", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Double[]", "int", null),
        new ExpectedResult("java.lang.Double[]", "int[]", null),
        new ExpectedResult("java.lang.Double[]", "long", null),
        new ExpectedResult("java.lang.Double[]", "long[]", null),
        new ExpectedResult("java.lang.Double[]", "double", null),
        new ExpectedResult("java.lang.Double[]", "double[]", null),
        new ExpectedResult("java.lang.Double[]", "float", null),
        new ExpectedResult("java.lang.Double[]", "float[]", null),
        new ExpectedResult("java.lang.Double[]", "boolean", null),
        new ExpectedResult("java.lang.Double[]", "boolean[]", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Integer", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Long", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Double", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Double[]", "sourceVal"),
        new ExpectedResult("java.lang.Double[]", "java.lang.Float", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Boolean", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Double[]", "java.util.Date", null),
        new ExpectedResult("java.lang.Double[]", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Double[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Double[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Double[]", "java.sql.Time", null),
        new ExpectedResult("java.lang.Double[]", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Double[]", "java.sql.Date", null),
        new ExpectedResult("java.lang.Double[]", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.String", null),
        new ExpectedResult("java.lang.Double[]", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Double[]", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Double[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Double[]", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Double[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Float", "int", "(int)(sourceVal == null ? 0.0f : sourceVal.floatValue())"),
        new ExpectedResult("java.lang.Float", "int[]", null),
        new ExpectedResult("java.lang.Float", "long", "(long)(sourceVal == null ? 0.0f : sourceVal.floatValue())"),
        new ExpectedResult("java.lang.Float", "long[]", null),
        new ExpectedResult("java.lang.Float", "double", "(double)(sourceVal == null ? 0.0f : sourceVal.floatValue())"),
        new ExpectedResult("java.lang.Float", "double[]", null),
        new ExpectedResult("java.lang.Float", "float", "(sourceVal == null ? 0.0f : sourceVal.floatValue())"),
        new ExpectedResult("java.lang.Float", "float[]", null),
        new ExpectedResult("java.lang.Float", "boolean", "((sourceVal == null ? 0.0f : sourceVal.floatValue()) != 0.0f)"),
        new ExpectedResult("java.lang.Float", "boolean[]", null),
        new ExpectedResult("java.lang.Float", "java.lang.Integer", "new java.lang.Integer((int)(sourceVal == null ? 0.0f : sourceVal.floatValue()))"),
        new ExpectedResult("java.lang.Float", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Float", "java.lang.Long", "new java.lang.Long((long)(sourceVal == null ? 0.0f : sourceVal.floatValue()))"),
        new ExpectedResult("java.lang.Float", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Float", "java.lang.Double", "new java.lang.Double((double)(sourceVal == null ? 0.0f : sourceVal.floatValue()))"),
        new ExpectedResult("java.lang.Float", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Float", "java.lang.Float", "sourceVal"),
        new ExpectedResult("java.lang.Float", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Float", "java.lang.Boolean", "new java.lang.Boolean(((sourceVal == null ? 0.0f : sourceVal.floatValue()) != 0.0f))"),
        new ExpectedResult("java.lang.Float", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Float", "java.util.Date", null),
        new ExpectedResult("java.lang.Float", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Float", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Float", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Float", "java.sql.Time", null),
        new ExpectedResult("java.lang.Float", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Float", "java.sql.Date", null),
        new ExpectedResult("java.lang.Float", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Float", "java.lang.String", "(sourceVal == null ? null : sourceVal.toString())"),
        new ExpectedResult("java.lang.Float", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Float", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Float", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Float", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Float", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Float[]", "int", null),
        new ExpectedResult("java.lang.Float[]", "int[]", null),
        new ExpectedResult("java.lang.Float[]", "long", null),
        new ExpectedResult("java.lang.Float[]", "long[]", null),
        new ExpectedResult("java.lang.Float[]", "double", null),
        new ExpectedResult("java.lang.Float[]", "double[]", null),
        new ExpectedResult("java.lang.Float[]", "float", null),
        new ExpectedResult("java.lang.Float[]", "float[]", null),
        new ExpectedResult("java.lang.Float[]", "boolean", null),
        new ExpectedResult("java.lang.Float[]", "boolean[]", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Integer", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Long", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Double", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Float", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Float[]", "sourceVal"),
        new ExpectedResult("java.lang.Float[]", "java.lang.Boolean", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Float[]", "java.util.Date", null),
        new ExpectedResult("java.lang.Float[]", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Float[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Float[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Float[]", "java.sql.Time", null),
        new ExpectedResult("java.lang.Float[]", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Float[]", "java.sql.Date", null),
        new ExpectedResult("java.lang.Float[]", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.String", null),
        new ExpectedResult("java.lang.Float[]", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Float[]", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Float[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Float[]", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Float[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Boolean", "int", "((sourceVal == null ? false : sourceVal.booleanValue()) ? 1 : 0)"),
        new ExpectedResult("java.lang.Boolean", "int[]", null),
        new ExpectedResult("java.lang.Boolean", "long", "((sourceVal == null ? false : sourceVal.booleanValue()) ? 1 : 0)"),
        new ExpectedResult("java.lang.Boolean", "long[]", null),
        new ExpectedResult("java.lang.Boolean", "double", "((sourceVal == null ? false : sourceVal.booleanValue()) ? 1.0 : 0.0)"),
        new ExpectedResult("java.lang.Boolean", "double[]", null),
        new ExpectedResult("java.lang.Boolean", "float", "((sourceVal == null ? false : sourceVal.booleanValue()) ? 1.0f : 0.0f)"),
        new ExpectedResult("java.lang.Boolean", "float[]", null),
        new ExpectedResult("java.lang.Boolean", "boolean", "(sourceVal == null ? false : sourceVal.booleanValue())"),
        new ExpectedResult("java.lang.Boolean", "boolean[]", null),
        new ExpectedResult("java.lang.Boolean", "java.lang.Integer", "new java.lang.Integer(((sourceVal == null ? false : sourceVal.booleanValue()) ? 1 : 0))"),
        new ExpectedResult("java.lang.Boolean", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Boolean", "java.lang.Long", "new java.lang.Long(((sourceVal == null ? false : sourceVal.booleanValue()) ? 1 : 0))"),
        new ExpectedResult("java.lang.Boolean", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Boolean", "java.lang.Double", "new java.lang.Double(((sourceVal == null ? false : sourceVal.booleanValue()) ? 1.0 : 0.0))"),
        new ExpectedResult("java.lang.Boolean", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Boolean", "java.lang.Float", "new java.lang.Float(((sourceVal == null ? false : sourceVal.booleanValue()) ? 1.0f : 0.0f))"),
        new ExpectedResult("java.lang.Boolean", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Boolean", "java.lang.Boolean", "sourceVal"),
        new ExpectedResult("java.lang.Boolean", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.Boolean", "java.util.Date", null),
        new ExpectedResult("java.lang.Boolean", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Boolean", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Boolean", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Boolean", "java.sql.Time", null),
        new ExpectedResult("java.lang.Boolean", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Boolean", "java.sql.Date", null),
        new ExpectedResult("java.lang.Boolean", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Boolean", "java.lang.String", "(sourceVal == null ? null : sourceVal.toString())"),
        new ExpectedResult("java.lang.Boolean", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Boolean", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Boolean", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Boolean", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Boolean", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.Boolean[]", "int", null),
        new ExpectedResult("java.lang.Boolean[]", "int[]", null),
        new ExpectedResult("java.lang.Boolean[]", "long", null),
        new ExpectedResult("java.lang.Boolean[]", "long[]", null),
        new ExpectedResult("java.lang.Boolean[]", "double", null),
        new ExpectedResult("java.lang.Boolean[]", "double[]", null),
        new ExpectedResult("java.lang.Boolean[]", "float", null),
        new ExpectedResult("java.lang.Boolean[]", "float[]", null),
        new ExpectedResult("java.lang.Boolean[]", "boolean", null),
        new ExpectedResult("java.lang.Boolean[]", "boolean[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Integer", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Long", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Double", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Float", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Boolean", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.Boolean[]", "sourceVal"),
        new ExpectedResult("java.lang.Boolean[]", "java.util.Date", null),
        new ExpectedResult("java.lang.Boolean[]", "java.util.Date[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.Boolean[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.sql.Time", null),
        new ExpectedResult("java.lang.Boolean[]", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.sql.Date", null),
        new ExpectedResult("java.lang.Boolean[]", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.String", null),
        new ExpectedResult("java.lang.Boolean[]", "java.lang.String[]", null),
        new ExpectedResult("java.lang.Boolean[]", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.Boolean[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.Boolean[]", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.Boolean[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.util.Date", "int", null),
        new ExpectedResult("java.util.Date", "int[]", null),
        new ExpectedResult("java.util.Date", "long", "(sourceVal == null ? 0 : sourceVal.getTime())"),
        new ExpectedResult("java.util.Date", "long[]", null),
        new ExpectedResult("java.util.Date", "double", null),
        new ExpectedResult("java.util.Date", "double[]", null),
        new ExpectedResult("java.util.Date", "float", null),
        new ExpectedResult("java.util.Date", "float[]", null),
        new ExpectedResult("java.util.Date", "boolean", null),
        new ExpectedResult("java.util.Date", "boolean[]", null),
        new ExpectedResult("java.util.Date", "java.lang.Integer", null),
        new ExpectedResult("java.util.Date", "java.lang.Integer[]", null),
        new ExpectedResult("java.util.Date", "java.lang.Long", "new java.lang.Long((sourceVal == null ? 0 : sourceVal.getTime()))"),
        new ExpectedResult("java.util.Date", "java.lang.Long[]", null),
        new ExpectedResult("java.util.Date", "java.lang.Double", null),
        new ExpectedResult("java.util.Date", "java.lang.Double[]", null),
        new ExpectedResult("java.util.Date", "java.lang.Float", null),
        new ExpectedResult("java.util.Date", "java.lang.Float[]", null),
        new ExpectedResult("java.util.Date", "java.lang.Boolean", null),
        new ExpectedResult("java.util.Date", "java.lang.Boolean[]", null),
        new ExpectedResult("java.util.Date", "java.util.Date", "sourceVal"),
        new ExpectedResult("java.util.Date", "java.util.Date[]", null),
        new ExpectedResult("java.util.Date", "java.sql.Timestamp", "(sourceVal == null ? null : new java.sql.Timestamp(sourceVal.getTime()))"),
        new ExpectedResult("java.util.Date", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.util.Date", "java.sql.Time", "(sourceVal == null ? null : new java.sql.Time(sourceVal.getTime()))"),
        new ExpectedResult("java.util.Date", "java.sql.Time[]", null),
        new ExpectedResult("java.util.Date", "java.sql.Date", "(sourceVal == null ? null : new java.sql.Date(sourceVal.getTime()))"),
        new ExpectedResult("java.util.Date", "java.sql.Date[]", null),
        new ExpectedResult("java.util.Date", "java.lang.String", "(sourceVal == null ? null : new java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ssZ\").format(sourceVal))"),
        new ExpectedResult("java.util.Date", "java.lang.String[]", null),
        new ExpectedResult("java.util.Date", "com.example.UserClass1", null),
        new ExpectedResult("java.util.Date", "com.example.UserClass1[]", null),
        new ExpectedResult("java.util.Date", "com.example.UserClass2", null),
        new ExpectedResult("java.util.Date", "com.example.UserClass2[]", null),
        new ExpectedResult("java.util.Date[]", "int", null),
        new ExpectedResult("java.util.Date[]", "int[]", null),
        new ExpectedResult("java.util.Date[]", "long", null),
        new ExpectedResult("java.util.Date[]", "long[]", null),
        new ExpectedResult("java.util.Date[]", "double", null),
        new ExpectedResult("java.util.Date[]", "double[]", null),
        new ExpectedResult("java.util.Date[]", "float", null),
        new ExpectedResult("java.util.Date[]", "float[]", null),
        new ExpectedResult("java.util.Date[]", "boolean", null),
        new ExpectedResult("java.util.Date[]", "boolean[]", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Integer", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Long", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Long[]", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Double", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Double[]", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Float", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Float[]", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Boolean", null),
        new ExpectedResult("java.util.Date[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.util.Date[]", "java.util.Date", null),
        new ExpectedResult("java.util.Date[]", "java.util.Date[]", "sourceVal"),
        new ExpectedResult("java.util.Date[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.util.Date[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.util.Date[]", "java.sql.Time", null),
        new ExpectedResult("java.util.Date[]", "java.sql.Time[]", null),
        new ExpectedResult("java.util.Date[]", "java.sql.Date", null),
        new ExpectedResult("java.util.Date[]", "java.sql.Date[]", null),
        new ExpectedResult("java.util.Date[]", "java.lang.String", null),
        new ExpectedResult("java.util.Date[]", "java.lang.String[]", null),
        new ExpectedResult("java.util.Date[]", "com.example.UserClass1", null),
        new ExpectedResult("java.util.Date[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.util.Date[]", "com.example.UserClass2", null),
        new ExpectedResult("java.util.Date[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.sql.Timestamp", "int", null),
        new ExpectedResult("java.sql.Timestamp", "int[]", null),
        new ExpectedResult("java.sql.Timestamp", "long", "(sourceVal == null ? 0 : sourceVal.getTime())"),
        new ExpectedResult("java.sql.Timestamp", "long[]", null),
        new ExpectedResult("java.sql.Timestamp", "double", null),
        new ExpectedResult("java.sql.Timestamp", "double[]", null),
        new ExpectedResult("java.sql.Timestamp", "float", null),
        new ExpectedResult("java.sql.Timestamp", "float[]", null),
        new ExpectedResult("java.sql.Timestamp", "boolean", null),
        new ExpectedResult("java.sql.Timestamp", "boolean[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Integer", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Integer[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Long", "new java.lang.Long((sourceVal == null ? 0 : sourceVal.getTime()))"),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Long[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Double", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Double[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Float", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Float[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Boolean", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.Boolean[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.util.Date", "sourceVal"),
        new ExpectedResult("java.sql.Timestamp", "java.util.Date[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.sql.Timestamp", "sourceVal"),
        new ExpectedResult("java.sql.Timestamp", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.sql.Time", "(sourceVal == null ? null : new java.sql.Time(sourceVal.getTime()))"),
        new ExpectedResult("java.sql.Timestamp", "java.sql.Time[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.sql.Date", "(sourceVal == null ? null : new java.sql.Date(sourceVal.getTime()))"),
        new ExpectedResult("java.sql.Timestamp", "java.sql.Date[]", null),
        new ExpectedResult("java.sql.Timestamp", "java.lang.String", "(sourceVal == null ? null : new java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ssZ\").format(sourceVal))"),
        new ExpectedResult("java.sql.Timestamp", "java.lang.String[]", null),
        new ExpectedResult("java.sql.Timestamp", "com.example.UserClass1", null),
        new ExpectedResult("java.sql.Timestamp", "com.example.UserClass1[]", null),
        new ExpectedResult("java.sql.Timestamp", "com.example.UserClass2", null),
        new ExpectedResult("java.sql.Timestamp", "com.example.UserClass2[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "int", null),
        new ExpectedResult("java.sql.Timestamp[]", "int[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "long", null),
        new ExpectedResult("java.sql.Timestamp[]", "long[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "double", null),
        new ExpectedResult("java.sql.Timestamp[]", "double[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "float", null),
        new ExpectedResult("java.sql.Timestamp[]", "float[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "boolean", null),
        new ExpectedResult("java.sql.Timestamp[]", "boolean[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Integer", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Long", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Long[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Double", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Double[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Float", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Float[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Boolean", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.util.Date", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.util.Date[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.sql.Timestamp[]", "sourceVal"),
        new ExpectedResult("java.sql.Timestamp[]", "java.sql.Time", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.sql.Time[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.sql.Date", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.sql.Date[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.String", null),
        new ExpectedResult("java.sql.Timestamp[]", "java.lang.String[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "com.example.UserClass1", null),
        new ExpectedResult("java.sql.Timestamp[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.sql.Timestamp[]", "com.example.UserClass2", null),
        new ExpectedResult("java.sql.Timestamp[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.sql.Time", "int", null),
        new ExpectedResult("java.sql.Time", "int[]", null),
        new ExpectedResult("java.sql.Time", "long", "(sourceVal == null ? 0 : sourceVal.getTime())"),
        new ExpectedResult("java.sql.Time", "long[]", null),
        new ExpectedResult("java.sql.Time", "double", null),
        new ExpectedResult("java.sql.Time", "double[]", null),
        new ExpectedResult("java.sql.Time", "float", null),
        new ExpectedResult("java.sql.Time", "float[]", null),
        new ExpectedResult("java.sql.Time", "boolean", null),
        new ExpectedResult("java.sql.Time", "boolean[]", null),
        new ExpectedResult("java.sql.Time", "java.lang.Integer", null),
        new ExpectedResult("java.sql.Time", "java.lang.Integer[]", null),
        new ExpectedResult("java.sql.Time", "java.lang.Long", "new java.lang.Long((sourceVal == null ? 0 : sourceVal.getTime()))"),
        new ExpectedResult("java.sql.Time", "java.lang.Long[]", null),
        new ExpectedResult("java.sql.Time", "java.lang.Double", null),
        new ExpectedResult("java.sql.Time", "java.lang.Double[]", null),
        new ExpectedResult("java.sql.Time", "java.lang.Float", null),
        new ExpectedResult("java.sql.Time", "java.lang.Float[]", null),
        new ExpectedResult("java.sql.Time", "java.lang.Boolean", null),
        new ExpectedResult("java.sql.Time", "java.lang.Boolean[]", null),
        new ExpectedResult("java.sql.Time", "java.util.Date", "sourceVal"),
        new ExpectedResult("java.sql.Time", "java.util.Date[]", null),
        new ExpectedResult("java.sql.Time", "java.sql.Timestamp", "(sourceVal == null ? null : new java.sql.Timestamp(sourceVal.getTime()))"),
        new ExpectedResult("java.sql.Time", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.sql.Time", "java.sql.Time", "sourceVal"),
        new ExpectedResult("java.sql.Time", "java.sql.Time[]", null),
        new ExpectedResult("java.sql.Time", "java.sql.Date", null),
        new ExpectedResult("java.sql.Time", "java.sql.Date[]", null),
        new ExpectedResult("java.sql.Time", "java.lang.String", "(sourceVal == null ? null : new java.text.SimpleDateFormat(\"HH:mm:ssZ\").format(sourceVal))"),
        new ExpectedResult("java.sql.Time", "java.lang.String[]", null),
        new ExpectedResult("java.sql.Time", "com.example.UserClass1", null),
        new ExpectedResult("java.sql.Time", "com.example.UserClass1[]", null),
        new ExpectedResult("java.sql.Time", "com.example.UserClass2", null),
        new ExpectedResult("java.sql.Time", "com.example.UserClass2[]", null),
        new ExpectedResult("java.sql.Time[]", "int", null),
        new ExpectedResult("java.sql.Time[]", "int[]", null),
        new ExpectedResult("java.sql.Time[]", "long", null),
        new ExpectedResult("java.sql.Time[]", "long[]", null),
        new ExpectedResult("java.sql.Time[]", "double", null),
        new ExpectedResult("java.sql.Time[]", "double[]", null),
        new ExpectedResult("java.sql.Time[]", "float", null),
        new ExpectedResult("java.sql.Time[]", "float[]", null),
        new ExpectedResult("java.sql.Time[]", "boolean", null),
        new ExpectedResult("java.sql.Time[]", "boolean[]", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Integer", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Long", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Long[]", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Double", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Double[]", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Float", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Float[]", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Boolean", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.sql.Time[]", "java.util.Date", null),
        new ExpectedResult("java.sql.Time[]", "java.util.Date[]", null),
        new ExpectedResult("java.sql.Time[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.sql.Time[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.sql.Time[]", "java.sql.Time", null),
        new ExpectedResult("java.sql.Time[]", "java.sql.Time[]", "sourceVal"),
        new ExpectedResult("java.sql.Time[]", "java.sql.Date", null),
        new ExpectedResult("java.sql.Time[]", "java.sql.Date[]", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.String", null),
        new ExpectedResult("java.sql.Time[]", "java.lang.String[]", null),
        new ExpectedResult("java.sql.Time[]", "com.example.UserClass1", null),
        new ExpectedResult("java.sql.Time[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.sql.Time[]", "com.example.UserClass2", null),
        new ExpectedResult("java.sql.Time[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.sql.Date", "int", null),
        new ExpectedResult("java.sql.Date", "int[]", null),
        new ExpectedResult("java.sql.Date", "long", "(sourceVal == null ? 0 : sourceVal.getTime())"),
        new ExpectedResult("java.sql.Date", "long[]", null),
        new ExpectedResult("java.sql.Date", "double", null),
        new ExpectedResult("java.sql.Date", "double[]", null),
        new ExpectedResult("java.sql.Date", "float", null),
        new ExpectedResult("java.sql.Date", "float[]", null),
        new ExpectedResult("java.sql.Date", "boolean", null),
        new ExpectedResult("java.sql.Date", "boolean[]", null),
        new ExpectedResult("java.sql.Date", "java.lang.Integer", null),
        new ExpectedResult("java.sql.Date", "java.lang.Integer[]", null),
        new ExpectedResult("java.sql.Date", "java.lang.Long", "new java.lang.Long((sourceVal == null ? 0 : sourceVal.getTime()))"),
        new ExpectedResult("java.sql.Date", "java.lang.Long[]", null),
        new ExpectedResult("java.sql.Date", "java.lang.Double", null),
        new ExpectedResult("java.sql.Date", "java.lang.Double[]", null),
        new ExpectedResult("java.sql.Date", "java.lang.Float", null),
        new ExpectedResult("java.sql.Date", "java.lang.Float[]", null),
        new ExpectedResult("java.sql.Date", "java.lang.Boolean", null),
        new ExpectedResult("java.sql.Date", "java.lang.Boolean[]", null),
        new ExpectedResult("java.sql.Date", "java.util.Date", "sourceVal"),
        new ExpectedResult("java.sql.Date", "java.util.Date[]", null),
        new ExpectedResult("java.sql.Date", "java.sql.Timestamp", "(sourceVal == null ? null : new java.sql.Timestamp(sourceVal.getTime()))"),
        new ExpectedResult("java.sql.Date", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.sql.Date", "java.sql.Time", null),
        new ExpectedResult("java.sql.Date", "java.sql.Time[]", null),
        new ExpectedResult("java.sql.Date", "java.sql.Date", "sourceVal"),
        new ExpectedResult("java.sql.Date", "java.sql.Date[]", null),
        new ExpectedResult("java.sql.Date", "java.lang.String", "(sourceVal == null ? null : new java.text.SimpleDateFormat(\"yyyy-MM-dd\").format(sourceVal))"),
        new ExpectedResult("java.sql.Date", "java.lang.String[]", null),
        new ExpectedResult("java.sql.Date", "com.example.UserClass1", null),
        new ExpectedResult("java.sql.Date", "com.example.UserClass1[]", null),
        new ExpectedResult("java.sql.Date", "com.example.UserClass2", null),
        new ExpectedResult("java.sql.Date", "com.example.UserClass2[]", null),
        new ExpectedResult("java.sql.Date[]", "int", null),
        new ExpectedResult("java.sql.Date[]", "int[]", null),
        new ExpectedResult("java.sql.Date[]", "long", null),
        new ExpectedResult("java.sql.Date[]", "long[]", null),
        new ExpectedResult("java.sql.Date[]", "double", null),
        new ExpectedResult("java.sql.Date[]", "double[]", null),
        new ExpectedResult("java.sql.Date[]", "float", null),
        new ExpectedResult("java.sql.Date[]", "float[]", null),
        new ExpectedResult("java.sql.Date[]", "boolean", null),
        new ExpectedResult("java.sql.Date[]", "boolean[]", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Integer", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Long", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Long[]", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Double", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Double[]", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Float", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Float[]", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Boolean", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.sql.Date[]", "java.util.Date", null),
        new ExpectedResult("java.sql.Date[]", "java.util.Date[]", null),
        new ExpectedResult("java.sql.Date[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.sql.Date[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.sql.Date[]", "java.sql.Time", null),
        new ExpectedResult("java.sql.Date[]", "java.sql.Time[]", null),
        new ExpectedResult("java.sql.Date[]", "java.sql.Date", null),
        new ExpectedResult("java.sql.Date[]", "java.sql.Date[]", "sourceVal"),
        new ExpectedResult("java.sql.Date[]", "java.lang.String", null),
        new ExpectedResult("java.sql.Date[]", "java.lang.String[]", null),
        new ExpectedResult("java.sql.Date[]", "com.example.UserClass1", null),
        new ExpectedResult("java.sql.Date[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.sql.Date[]", "com.example.UserClass2", null),
        new ExpectedResult("java.sql.Date[]", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.String", "int", "(sourceVal == null ? 0 : Integer.valueOf(sourceVal).intValue())"),
        new ExpectedResult("java.lang.String", "int[]", null),
        new ExpectedResult("java.lang.String", "long", "(sourceVal == null ? 0 : Long.valueOf(sourceVal).longValue())"),
        new ExpectedResult("java.lang.String", "long[]", null),
        new ExpectedResult("java.lang.String", "double", "(sourceVal == null ? 0.0 : Double.valueOf(sourceVal).doubleValue())"),
        new ExpectedResult("java.lang.String", "double[]", null),
        new ExpectedResult("java.lang.String", "float", "(sourceVal == null ? 0.0f : Float.valueOf(sourceVal).floatValue())"),
        new ExpectedResult("java.lang.String", "float[]", null),
        new ExpectedResult("java.lang.String", "boolean", "(sourceVal == null ? false : Boolean.valueOf(sourceVal).booleanValue())"),
        new ExpectedResult("java.lang.String", "boolean[]", null),
        new ExpectedResult("java.lang.String", "java.lang.Integer", "(sourceVal == null ? null : Integer.valueOf(sourceVal))"),
        new ExpectedResult("java.lang.String", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.String", "java.lang.Long", "(sourceVal == null ? null : Long.valueOf(sourceVal))"),
        new ExpectedResult("java.lang.String", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.String", "java.lang.Double", "(sourceVal == null ? null : Double.valueOf(sourceVal))"),
        new ExpectedResult("java.lang.String", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.String", "java.lang.Float", "(sourceVal == null ? null : Float.valueOf(sourceVal))"),
        new ExpectedResult("java.lang.String", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.String", "java.lang.Boolean", "(sourceVal == null ? null : Boolean.valueOf(sourceVal))"),
        new ExpectedResult("java.lang.String", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.String", "java.util.Date", "(sourceVal == null ? null : new java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ssZ\").parse(sourceVal))"),
        new ExpectedResult("java.lang.String", "java.util.Date[]", null),
        new ExpectedResult("java.lang.String", "java.sql.Timestamp", "(sourceVal == null ? null : new java.sql.Timestamp(new java.text.SimpleDateFormat(\"yyyy-MM-dd HH:mm:ssZ\").parse(sourceVal).getTime()))"),
        new ExpectedResult("java.lang.String", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.String", "java.sql.Time", "(sourceVal == null ? null : new java.sql.Time(new java.text.SimpleDateFormat(\"HH:mm:ssZ\").parse(sourceVal).getTime()))"),
        new ExpectedResult("java.lang.String", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.String", "java.sql.Date", "(sourceVal == null ? null : new java.sql.Date(new java.text.SimpleDateFormat(\"yyyy-MM-dd\").parse(sourceVal).getTime()))"),
        new ExpectedResult("java.lang.String", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.String", "java.lang.String", "sourceVal"),
        new ExpectedResult("java.lang.String", "java.lang.String[]", null),
        new ExpectedResult("java.lang.String", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.String", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.String", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.String", "com.example.UserClass2[]", null),
        new ExpectedResult("java.lang.String[]", "int", null),
        new ExpectedResult("java.lang.String[]", "int[]", null),
        new ExpectedResult("java.lang.String[]", "long", null),
        new ExpectedResult("java.lang.String[]", "long[]", null),
        new ExpectedResult("java.lang.String[]", "double", null),
        new ExpectedResult("java.lang.String[]", "double[]", null),
        new ExpectedResult("java.lang.String[]", "float", null),
        new ExpectedResult("java.lang.String[]", "float[]", null),
        new ExpectedResult("java.lang.String[]", "boolean", null),
        new ExpectedResult("java.lang.String[]", "boolean[]", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Integer", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Integer[]", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Long", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Long[]", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Double", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Double[]", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Float", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Float[]", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Boolean", null),
        new ExpectedResult("java.lang.String[]", "java.lang.Boolean[]", null),
        new ExpectedResult("java.lang.String[]", "java.util.Date", null),
        new ExpectedResult("java.lang.String[]", "java.util.Date[]", null),
        new ExpectedResult("java.lang.String[]", "java.sql.Timestamp", null),
        new ExpectedResult("java.lang.String[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("java.lang.String[]", "java.sql.Time", null),
        new ExpectedResult("java.lang.String[]", "java.sql.Time[]", null),
        new ExpectedResult("java.lang.String[]", "java.sql.Date", null),
        new ExpectedResult("java.lang.String[]", "java.sql.Date[]", null),
        new ExpectedResult("java.lang.String[]", "java.lang.String", null),
        new ExpectedResult("java.lang.String[]", "java.lang.String[]", "sourceVal"),
        new ExpectedResult("java.lang.String[]", "com.example.UserClass1", null),
        new ExpectedResult("java.lang.String[]", "com.example.UserClass1[]", null),
        new ExpectedResult("java.lang.String[]", "com.example.UserClass2", null),
        new ExpectedResult("java.lang.String[]", "com.example.UserClass2[]", null),
        new ExpectedResult("com.example.UserClass1", "int", null),
        new ExpectedResult("com.example.UserClass1", "int[]", null),
        new ExpectedResult("com.example.UserClass1", "long", null),
        new ExpectedResult("com.example.UserClass1", "long[]", null),
        new ExpectedResult("com.example.UserClass1", "double", null),
        new ExpectedResult("com.example.UserClass1", "double[]", null),
        new ExpectedResult("com.example.UserClass1", "float", null),
        new ExpectedResult("com.example.UserClass1", "float[]", null),
        new ExpectedResult("com.example.UserClass1", "boolean", null),
        new ExpectedResult("com.example.UserClass1", "boolean[]", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Integer", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Integer[]", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Long", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Long[]", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Double", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Double[]", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Float", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Float[]", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Boolean", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.Boolean[]", null),
        new ExpectedResult("com.example.UserClass1", "java.util.Date", null),
        new ExpectedResult("com.example.UserClass1", "java.util.Date[]", null),
        new ExpectedResult("com.example.UserClass1", "java.sql.Timestamp", null),
        new ExpectedResult("com.example.UserClass1", "java.sql.Timestamp[]", null),
        new ExpectedResult("com.example.UserClass1", "java.sql.Time", null),
        new ExpectedResult("com.example.UserClass1", "java.sql.Time[]", null),
        new ExpectedResult("com.example.UserClass1", "java.sql.Date", null),
        new ExpectedResult("com.example.UserClass1", "java.sql.Date[]", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.String", null),
        new ExpectedResult("com.example.UserClass1", "java.lang.String[]", null),
        new ExpectedResult("com.example.UserClass1", "com.example.UserClass1", "sourceVal"),
        new ExpectedResult("com.example.UserClass1", "com.example.UserClass1[]", null),
        new ExpectedResult("com.example.UserClass1", "com.example.UserClass2", null),
        new ExpectedResult("com.example.UserClass1", "com.example.UserClass2[]", null),
        new ExpectedResult("com.example.UserClass1[]", "int", null),
        new ExpectedResult("com.example.UserClass1[]", "int[]", null),
        new ExpectedResult("com.example.UserClass1[]", "long", null),
        new ExpectedResult("com.example.UserClass1[]", "long[]", null),
        new ExpectedResult("com.example.UserClass1[]", "double", null),
        new ExpectedResult("com.example.UserClass1[]", "double[]", null),
        new ExpectedResult("com.example.UserClass1[]", "float", null),
        new ExpectedResult("com.example.UserClass1[]", "float[]", null),
        new ExpectedResult("com.example.UserClass1[]", "boolean", null),
        new ExpectedResult("com.example.UserClass1[]", "boolean[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Integer", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Integer[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Long", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Long[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Double", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Double[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Float", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Float[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Boolean", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.Boolean[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.util.Date", null),
        new ExpectedResult("com.example.UserClass1[]", "java.util.Date[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.sql.Timestamp", null),
        new ExpectedResult("com.example.UserClass1[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.sql.Time", null),
        new ExpectedResult("com.example.UserClass1[]", "java.sql.Time[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.sql.Date", null),
        new ExpectedResult("com.example.UserClass1[]", "java.sql.Date[]", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.String", null),
        new ExpectedResult("com.example.UserClass1[]", "java.lang.String[]", null),
        new ExpectedResult("com.example.UserClass1[]", "com.example.UserClass1", null),
        new ExpectedResult("com.example.UserClass1[]", "com.example.UserClass1[]", "sourceVal"),
        new ExpectedResult("com.example.UserClass1[]", "com.example.UserClass2", null),
        new ExpectedResult("com.example.UserClass1[]", "com.example.UserClass2[]", null),
        new ExpectedResult("com.example.UserClass2", "int", null),
        new ExpectedResult("com.example.UserClass2", "int[]", null),
        new ExpectedResult("com.example.UserClass2", "long", null),
        new ExpectedResult("com.example.UserClass2", "long[]", null),
        new ExpectedResult("com.example.UserClass2", "double", null),
        new ExpectedResult("com.example.UserClass2", "double[]", null),
        new ExpectedResult("com.example.UserClass2", "float", null),
        new ExpectedResult("com.example.UserClass2", "float[]", null),
        new ExpectedResult("com.example.UserClass2", "boolean", null),
        new ExpectedResult("com.example.UserClass2", "boolean[]", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Integer", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Integer[]", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Long", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Long[]", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Double", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Double[]", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Float", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Float[]", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Boolean", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.Boolean[]", null),
        new ExpectedResult("com.example.UserClass2", "java.util.Date", null),
        new ExpectedResult("com.example.UserClass2", "java.util.Date[]", null),
        new ExpectedResult("com.example.UserClass2", "java.sql.Timestamp", null),
        new ExpectedResult("com.example.UserClass2", "java.sql.Timestamp[]", null),
        new ExpectedResult("com.example.UserClass2", "java.sql.Time", null),
        new ExpectedResult("com.example.UserClass2", "java.sql.Time[]", null),
        new ExpectedResult("com.example.UserClass2", "java.sql.Date", null),
        new ExpectedResult("com.example.UserClass2", "java.sql.Date[]", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.String", null),
        new ExpectedResult("com.example.UserClass2", "java.lang.String[]", null),
        new ExpectedResult("com.example.UserClass2", "com.example.UserClass1", null),
        new ExpectedResult("com.example.UserClass2", "com.example.UserClass1[]", null),
        new ExpectedResult("com.example.UserClass2", "com.example.UserClass2", "sourceVal"),
        new ExpectedResult("com.example.UserClass2", "com.example.UserClass2[]", null),
        new ExpectedResult("com.example.UserClass2[]", "int", null),
        new ExpectedResult("com.example.UserClass2[]", "int[]", null),
        new ExpectedResult("com.example.UserClass2[]", "long", null),
        new ExpectedResult("com.example.UserClass2[]", "long[]", null),
        new ExpectedResult("com.example.UserClass2[]", "double", null),
        new ExpectedResult("com.example.UserClass2[]", "double[]", null),
        new ExpectedResult("com.example.UserClass2[]", "float", null),
        new ExpectedResult("com.example.UserClass2[]", "float[]", null),
        new ExpectedResult("com.example.UserClass2[]", "boolean", null),
        new ExpectedResult("com.example.UserClass2[]", "boolean[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Integer", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Integer[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Long", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Long[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Double", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Double[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Float", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Float[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Boolean", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.Boolean[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.util.Date", null),
        new ExpectedResult("com.example.UserClass2[]", "java.util.Date[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.sql.Timestamp", null),
        new ExpectedResult("com.example.UserClass2[]", "java.sql.Timestamp[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.sql.Time", null),
        new ExpectedResult("com.example.UserClass2[]", "java.sql.Time[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.sql.Date", null),
        new ExpectedResult("com.example.UserClass2[]", "java.sql.Date[]", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.String", null),
        new ExpectedResult("com.example.UserClass2[]", "java.lang.String[]", null),
        new ExpectedResult("com.example.UserClass2[]", "com.example.UserClass1", null),
        new ExpectedResult("com.example.UserClass2[]", "com.example.UserClass1[]", null),
        new ExpectedResult("com.example.UserClass2[]", "com.example.UserClass2", null),
        new ExpectedResult("com.example.UserClass2[]", "com.example.UserClass2[]", "sourceVal")        
    };

    
    public void testTypeConversion()
    {
        final JavaTypeConverter converter = new JavaTypeConverter();
        for (int i = 0; i < expected.length; i++)
        {
            final String result = converter.typeConvert(expected[i].fromType, "sourceVal", expected[i].toType);
            assertEquals("Converting " + expected[i].fromType + " to " +
                expected[i].toType, expected[i].expected, result);
        } // for
    }

    
    public void testTypeConversionWithIgnore()
    {
        final JavaTypeConverter converter = new JavaTypeConverter();
        converter.setJavaTypeConversionIgnoreList("java.util.Date, java.sql.Timestamp");
        
        for (int i = 0; i < expected.length; i++)
        {
            final String result = converter.typeConvert(expected[i].fromType, "sourceVal", expected[i].toType);
            if (expected[i].fromType.equals("java.util.Date") ||
                expected[i].fromType.equals("java.sql.Timestamp") ||
                expected[i].toType.equals("java.util.Date") ||
                expected[i].toType.equals("java.sql.Timestamp") )
            {
                assertNull("Converting " + expected[i].fromType + " to " + expected[i].toType +
                    " should have been null, was: " + result, result);
            }
            else
            {
                assertEquals("Converting " + expected[i].fromType + " to " + expected[i].toType,
                    expected[i].expected, result);
            }
        } // for
    }
    
    /**
     * This method generates the "expected" source array, so it can be cut and
     * pasted from the console output to this class, AFTER is has been examined
     * by the programmer for accuracy (and/or sent through the compiler with
     * code from genActualSource()).
     * @see #genActualSource()
     */
    public static void generateExpectedSource()
    {
        final String[] knownTypes = 
        {
            "int", "long", "double", "float", "boolean",
            "java.lang.Integer", "java.lang.Long", "java.lang.Double", "java.lang.Float", "java.lang.Boolean",
            "java.util.Date", "java.sql.Timestamp", "java.sql.Time", "java.sql.Date",
            "java.lang.String", "com.example.UserClass1", "com.example.UserClass2"
        };
        
        final String[] typeSuffix = { "", "[]" };
        
        final JavaTypeConverter converter = new JavaTypeConverter();
        
        boolean firstOut = false;
        for (int fromIndex = 0; fromIndex < knownTypes.length; fromIndex++)
        {
            for (int fromSuffix = 0; fromSuffix < typeSuffix.length; fromSuffix++ )
            {
                for (int toIndex = 0; toIndex < knownTypes.length; toIndex++)
                {
                   for (int toSuffix = 0; toSuffix < typeSuffix.length; toSuffix++)
                   {
                       if (!firstOut)
                       {
                           firstOut = true;
                       }
                       else
                       {
                           System.out.println(",");
                       }
                       System.out.print("        new ExpectedResult(\"");
                       System.out.print(knownTypes[fromIndex] + typeSuffix[fromSuffix]);
                       System.out.print("\", \"");
                       System.out.print(knownTypes[toIndex] + typeSuffix[toSuffix]);
                       System.out.print("\", ");
                       final String result = converter.typeConvert(knownTypes[fromIndex] + typeSuffix[fromSuffix], "sourceVal", knownTypes[toIndex] + typeSuffix[toSuffix]);
                       if (result != null)
                       {
                          System.out.print("\"");
                          System.out.print(result);
                          System.out.print("\"");
                       }
                       else
                       {
                          System.out.print("null");                   
                       }
                       System.out.print(")");
                   } // for toSuffix
                } // for toIndex
            } // for fromSuffix
        } // for fromIndex
    }

    /**
     * This method generates source code that uses the variations.  The source
     * can then be sent through a compiler and checked for correctness.
     */
    public static void genActualSource()
    {
        final String[] knownTypes = 
        {
            "int", "long", "double", "float", "boolean",
            "java.lang.Integer", "java.lang.Long", "java.lang.Double", "java.lang.Float", "java.lang.Boolean",
            "java.util.Date", "java.sql.Timestamp", "java.sql.Time", "java.sql.Date",
            "java.lang.String"
        };

        final String[] typeSuffix = { "", "[]" };
        
        final JavaTypeConverter converter = new JavaTypeConverter();

        int sourceCounter = 1;
        System.out.println("public void testConversionCode() throws java.text.ParseException {");
        for (int fromIndex = 0; fromIndex < knownTypes.length; fromIndex++)
        {
            for (int fromSuffix = 0; fromSuffix < typeSuffix.length; fromSuffix++ )
            {
                for (int toIndex = 0; toIndex < knownTypes.length; toIndex++)
                {
                    for (int toSuffix = 0; toSuffix < typeSuffix.length; toSuffix++)
                    {
                       final String sourceLabel = "source" + sourceCounter;
                       final String result = converter.typeConvert(knownTypes[fromIndex] + typeSuffix[fromSuffix], sourceLabel, knownTypes[toIndex] + typeSuffix[toSuffix]);
                       if (result != null)
                       {
                          System.out.print("     ");
                          System.out.print(knownTypes[fromIndex] + typeSuffix[fromSuffix]);
                          System.out.print(" ");
                          System.out.print(sourceLabel);
                          if (typeSuffix[fromSuffix].equals("[]"))
                          {
                              System.out.print(" = new ");
                              System.out.print(knownTypes[fromIndex]);
                              System.out.println("[1];");
                          }
                          else if (knownTypes[fromIndex].indexOf(".") > 0)
                          {
                              System.out.println(" = null;");
                          }
                          else if (knownTypes[fromIndex].equals("boolean"))
                          {
                              System.out.println(" = false;");
                          }
                          else
                          {
                              System.out.println(" = 0;");
                          }
                          System.out.print("     ");
                          System.out.print(knownTypes[toIndex] + typeSuffix[toSuffix]);
                          System.out.print(" dest" + sourceCounter);
                          System.out.print(" = ");
                          System.out.print(result);
                          System.out.println(";");
                          sourceCounter++;
                       }
                       else
                       {
                           System.out.print("     // No conversion from ");
                           System.out.print(knownTypes[fromIndex] + typeSuffix[fromSuffix]);
                           System.out.print(" to ");
                           System.out.println(knownTypes[toIndex] + typeSuffix[toSuffix]);
                       }
                       System.out.println();
                    }
                } // for toIndex
            } // for fromSuffix
        } // for fromIndex
        System.out.println("}");
        
    }

    public static void main(String[] args) {
//        Uncomment to re-generated the "expected" if major mods are made        
//        JavaTypeConverterTest.generateExpectedSource();

//        Uncomment to re-generate source code to put through compiler to check syntax             
//        JavaTypeConverterTest.genActualSource();
        
        
        junit.textui.TestRunner.run(JavaTypeConverterTest.class);
    }
}
